name: Use Terraform and Deploy the snipeit application using Github Actions   

on:
  push: 
    branches:
      - master
  workflow_dispatch:
 
env: 
   ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
   ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
   ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
   ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
   ROOT_PATH: '../../Terraform'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.3

      - name: Deploy Infrastucture
            
        run: |
          cd ../../terraform
          terraform init --upgrade
          terraform plan
          terraform apply -auto-approve
